project:
  type: website
  resources:
    - cluster_data.json
  render:
    - "*.qmd"
 



execute:
  freeze: true
  echo: false
  warning: false
  message: false
  
website:
  title: "AD688 Team 1 Spring 2026"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: data_cleaning.qmd
        text: Data Cleaning
      - text: Research Questions
        menu:
          - href: ricardo2.qmd
            text: "Which Cities/States Have the Highest Job Growth?"
          - href: tianyi.qmd
            text: "Do Tech Hubs Still Dominate Hiring?"
          - href: zichen.qmd
            text: "Are remote jobs increasing or decreasing across industries?"
          - href: yingyi.qmd
            text: "Urban vs. Rural Job Markets for AI & Non-AI Careers"   
      - text: ML, BA & DS trends
        menu:
          - href: omar.qmd
            text: "Most In-Demand Skills for DS, BA & ML Roles"   
          - href: ai_ml_evolution.qmd
            text: "Have job descriptions evolved in 2024 to require AI/ML expertise?"
          - href: industry_hiring.qmd
            text: "What industries are hiring the most data scientists and why?"
          - href: ba_career_outlook.qmd
            text: "What is the career outlook for business analytics professionals?"
      - href: ml_model.qmd
        text: Machine Learning
      - href: cluster_finder.qmd
        text: Find Your Match
      - href: references.qmd  
        text: References 
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    bibliography: references.bib
    include-after-body:
      text: |
        <script src="/custom.js"></script>