project:
  type: website

execute:
  freeze: true
  
website:
  title: "AD688 Team 1 Spring 2026"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Research Questions
        menu:
          - href: omar.qmd
            text: "Most In-Demand Skills for DS, BA & ML Roles"
          - href: ricardo.qmd
            text: "Which Cities/States Have the Highest Job Growth?"
          - href: tianyi.qmd
            text: "Are Remote Jobs Increasing or Decreasing?"
          - href: zichen.qmd
            text: "Do Tech Hubs Still Dominate Hiring?"
          - href: yingyi.qmd
            text: "Urban vs. Rural Job Markets for AI & Non-AI Careers"
    
      - text: ML, BA & DS trends
        menu:
          - href: omar.qmd
            text: "Most In-Demand Skills for DS, BA & ML Roles"   
          - href: ai_ml_evolution.qmd
            text: "Have job descriptions evolved in 2024 to require AI/ML expertise?"
      - href: references.qmd  
        text: References 

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    bibliography: references.bib