{
  "hash": "649dde28a5d4e0f9ddb644b8c7b446f8",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Are remote jobs increasing or decreasing across industries?\"\nauthor: \"Zichen Zhang\"\ndate: today\nformat: \n  html:\n    bibliography: references.bib\n    toc: true\necho: false\njupyter: python3\n---\n\n\n\n# Introduction\n\n## Research Question\n\nThis section examines whether remote jobs are increasing or decreasing across industries in 2024 using the Lightcast job postings dataset. To answer this question, I compare the share of job postings labeled as remote across major industries from May to September 2024. Rather than focusing only on total posting volume, this analysis emphasizes the percentage of remote postings within each industry, which allows for a more meaningful comparison across sectors of very different sizes.\n\n## Why This Topic Matters\n\nRemote work remains an important feature of the post-pandemic labor market, but its direction is not uniform across industries. Prior research shows that the feasibility and prevalence of remote work vary substantially across sectors, occupations, and locations rather than following a single labor market pattern [@dingel2020; @hansen2023]. In addition, working from home appears to have remained a persistent employment arrangement rather than a purely temporary pandemic phenomenon [@barrero2021].\n\nThis topic is especially important for job seekers because remote-work availability can shape where they apply, which industries they prioritize, and how they evaluate flexibility in future career opportunities. More broadly, this section shares a common theme with recent remote-work research: remote-work opportunities vary across industries and do not move in one uniform direction across the labor market. Using Lightcast job postings, this section examines how remote job share changed across major industries from May to September 2024, with the goal of identifying whether remote opportunities increased, decreased, or diverged by sector.\n\n# Data Loading\n## Key Variables\n\nThis analysis uses the 2024 Lightcast job postings dataset to examine changes in remote job share across industries. To answer the research question, three variables are especially important: `NAICS_2022_6_NAME`, `REMOTE_TYPE_NAME`, and `POSTED`. Together, these fields provide the industry classification, the remote-work label, and the posting date needed to track industry-level changes in remote hiring over time.\n\nThese variables make it possible to analyze remote job postings at the industry-month level. Specifically, `NAICS_2022_6_NAME` identifies the industry of each posting, `REMOTE_TYPE_NAME` indicates whether the position is labeled as remote or non-remote, and `POSTED` provides the time information needed to compare remote job share from May to September 2024.\n\n::: {#d4476546 .cell message='false' execution_count=1}\n\n::: {.cell-output .cell-output-stdout}\n```\nTotal postings: 72,498\n                            NAICS_2022_6_NAME REMOTE_TYPE_NAME    POSTED\n0  Automotive Parts and Accessories Retailers           [None]  6/2/2024\n1                     Temporary Help Services           Remote  6/2/2024\n2                            Claims Adjusting           [None]  6/2/2024\n3                          Commercial Banking           [None]  6/2/2024\n4                       Unclassified Industry           [None]  6/2/2024\n```\n:::\n:::\n\n\nThe preview above confirms that the dataset contains the core variables required for this section. These fields provide the foundation for defining remote-work categories, calculating monthly remote job share, and comparing how remote opportunities changed across industries over time.\n\n# Defining Remote Work Categories\n## Industry Selection\nBefore measuring remote job trends across industries, I first restricted the analysis to the 15 industries with the largest number of job postings. This step keeps the comparison focused on the most active sectors in the dataset and reduces the influence of industries with relatively small posting counts. I also converted the posting date into monthly periods so that industry-level remote hiring patterns could be tracked consistently from May to September 2024.\n\n## Remote Work Classification\nBecause the raw values in `REMOTE_TYPE_NAME` are not fully standardized, I grouped postings into three broader categories: `Remote`, `Hybrid`, and `Onsite`. Postings explicitly labeled `Remote` were classified as remote roles, postings labeled `Hybrid Remote` were classified as hybrid roles, and postings labeled `Not Remote` or missing values such as `[None]` were grouped with on-site roles for simplicity.\n\nThis classification step makes the dataset easier to interpret and provides a more consistent basis for industry-level comparison. Since the goal of this section is to evaluate whether remote opportunities increased or decreased across industries, the later analysis focuses specifically on the share of postings classified as `Remote`.\n\n::: {#ef5dfe58 .cell message='false' execution_count=2}\n\n::: {.cell-output .cell-output-stdout}\n```\nmonth\n2024-05    15133\n2024-06    14381\n2024-07    12502\n2024-08    15105\n2024-09    15333\nFreq: M, Name: count, dtype: int64\nremote_group\nOnsite    57697\nRemote    12497\nHybrid     2260\nName: count, dtype: int64\n   REMOTE_TYPE_NAME remote_group\n29    Hybrid Remote       Hybrid\n10       Not Remote       Onsite\n1            Remote       Remote\n0            [None]       Onsite\n```\n:::\n:::\n\n\nThe output confirms that the postings can be organized into monthly periods and consolidated into broader remote-work categories for analysis. This preparation step supports a clearer comparison of remote job trends across industries over time.\n\n# Monthly Remote Share by Industry\nAfter defining the remote-work categories, the next step is to calculate the monthly share of postings classified as `Remote` within each industry. This measure is more informative than raw posting counts because industries differ substantially in overall hiring volume. By converting remote postings into percentages, I can compare remote hiring patterns across industries on a more consistent basis.\n\nThis percentage-based approach is also appropriate for the research question because the goal is not simply to identify which industries posted the most jobs, but rather to examine how remote hiring changed within each industry over time. Prior research suggests that remote-work feasibility and remote-job prevalence vary substantially across industries rather than following a single labor market pattern [@dingel2020; @hansen2023]. Measuring remote share at the industry-month level therefore provides a clearer basis for evaluating whether remote opportunities were increasing or decreasing across sectors.\n\n::: {#134d4340 .cell message='false' execution_count=3}\n\n::: {.cell-output .cell-output-display execution_count=3}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>month</th>\n      <th>NAICS_2022_6_NAME</th>\n      <th>share_pct</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>2</th>\n      <td>2024-05</td>\n      <td>Administrative Management and General Manageme...</td>\n      <td>4.411765</td>\n    </tr>\n    <tr>\n      <th>46</th>\n      <td>2024-06</td>\n      <td>Administrative Management and General Manageme...</td>\n      <td>5.805038</td>\n    </tr>\n    <tr>\n      <th>90</th>\n      <td>2024-07</td>\n      <td>Administrative Management and General Manageme...</td>\n      <td>9.486781</td>\n    </tr>\n    <tr>\n      <th>135</th>\n      <td>2024-08</td>\n      <td>Administrative Management and General Manageme...</td>\n      <td>17.567568</td>\n    </tr>\n    <tr>\n      <th>179</th>\n      <td>2024-09</td>\n      <td>Administrative Management and General Manageme...</td>\n      <td>6.068841</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>2024-05</td>\n      <td>All Other Professional, Scientific, and Techni...</td>\n      <td>16.746411</td>\n    </tr>\n    <tr>\n      <th>49</th>\n      <td>2024-06</td>\n      <td>All Other Professional, Scientific, and Techni...</td>\n      <td>17.647059</td>\n    </tr>\n    <tr>\n      <th>93</th>\n      <td>2024-07</td>\n      <td>All Other Professional, Scientific, and Techni...</td>\n      <td>23.474178</td>\n    </tr>\n    <tr>\n      <th>138</th>\n      <td>2024-08</td>\n      <td>All Other Professional, Scientific, and Techni...</td>\n      <td>27.192982</td>\n    </tr>\n    <tr>\n      <th>182</th>\n      <td>2024-09</td>\n      <td>All Other Professional, Scientific, and Techni...</td>\n      <td>23.444976</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>2024-05</td>\n      <td>Colleges, Universities, and Professional Schools</td>\n      <td>14.285714</td>\n    </tr>\n    <tr>\n      <th>52</th>\n      <td>2024-06</td>\n      <td>Colleges, Universities, and Professional Schools</td>\n      <td>17.355372</td>\n    </tr>\n    <tr>\n      <th>96</th>\n      <td>2024-07</td>\n      <td>Colleges, Universities, and Professional Schools</td>\n      <td>12.367491</td>\n    </tr>\n    <tr>\n      <th>141</th>\n      <td>2024-08</td>\n      <td>Colleges, Universities, and Professional Schools</td>\n      <td>17.314488</td>\n    </tr>\n    <tr>\n      <th>185</th>\n      <td>2024-09</td>\n      <td>Colleges, Universities, and Professional Schools</td>\n      <td>12.286689</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>2024-05</td>\n      <td>Commercial Banking</td>\n      <td>11.737089</td>\n    </tr>\n    <tr>\n      <th>55</th>\n      <td>2024-06</td>\n      <td>Commercial Banking</td>\n      <td>13.196481</td>\n    </tr>\n    <tr>\n      <th>99</th>\n      <td>2024-07</td>\n      <td>Commercial Banking</td>\n      <td>11.377246</td>\n    </tr>\n    <tr>\n      <th>144</th>\n      <td>2024-08</td>\n      <td>Commercial Banking</td>\n      <td>13.786008</td>\n    </tr>\n    <tr>\n      <th>188</th>\n      <td>2024-09</td>\n      <td>Commercial Banking</td>\n      <td>7.658643</td>\n    </tr>\n    <tr>\n      <th>14</th>\n      <td>2024-05</td>\n      <td>Computer Systems Design Services</td>\n      <td>15.661376</td>\n    </tr>\n    <tr>\n      <th>58</th>\n      <td>2024-06</td>\n      <td>Computer Systems Design Services</td>\n      <td>11.299435</td>\n    </tr>\n    <tr>\n      <th>102</th>\n      <td>2024-07</td>\n      <td>Computer Systems Design Services</td>\n      <td>7.956104</td>\n    </tr>\n    <tr>\n      <th>147</th>\n      <td>2024-08</td>\n      <td>Computer Systems Design Services</td>\n      <td>8.125819</td>\n    </tr>\n    <tr>\n      <th>191</th>\n      <td>2024-09</td>\n      <td>Computer Systems Design Services</td>\n      <td>7.272727</td>\n    </tr>\n    <tr>\n      <th>17</th>\n      <td>2024-05</td>\n      <td>Custom Computer Programming Services</td>\n      <td>20.049710</td>\n    </tr>\n    <tr>\n      <th>61</th>\n      <td>2024-06</td>\n      <td>Custom Computer Programming Services</td>\n      <td>12.186788</td>\n    </tr>\n    <tr>\n      <th>105</th>\n      <td>2024-07</td>\n      <td>Custom Computer Programming Services</td>\n      <td>14.345550</td>\n    </tr>\n    <tr>\n      <th>150</th>\n      <td>2024-08</td>\n      <td>Custom Computer Programming Services</td>\n      <td>27.751196</td>\n    </tr>\n    <tr>\n      <th>194</th>\n      <td>2024-09</td>\n      <td>Custom Computer Programming Services</td>\n      <td>9.576613</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nThe table above reports the monthly percentage of postings classified as remote within each industry. Focusing on remote share rather than raw counts helps control for differences in total posting volume across industries. This industry-month measure serves as the basis for the next section, where I compare how remote job share increased or decreased across industries over time.\n\n# Change in Remote Job Share from May to September 2024\n\n## Main Results\n\nTo evaluate whether remote jobs were increasing or decreasing across industries, I compared each industry’s remote job share in May 2024 with its corresponding share in September 2024. This comparison provides a straightforward summary of the overall direction of change during the period and helps identify which industries became more remote-oriented and which became less so.\n\n::: {#4f1b31f6 .cell message='false' execution_count=4}\n\n::: {.cell-output .cell-output-stdout}\n```\nmonth                                                 2024-05    2024-09  \\\nNAICS_2022_6_NAME                                                          \nGeneral Medical and Surgical Hospitals              13.302752  22.727273   \nUnclassified Industry                               14.232731  23.147257   \nAll Other Professional, Scientific, and Technic...  16.746411  23.444976   \nEmployment Placement Agencies                       14.802982  20.510096   \nOther Scientific and Technical Consulting Services  24.242424  27.319588   \nAdministrative Management and General Managemen...   4.411765   6.068841   \nColleges, Universities, and Professional Schools    14.285714  12.286689   \nTemporary Help Services                             30.063291  27.000000   \nOffices of Certified Public Accountants              3.619910   0.225225   \nDirect Health and Medical Insurance Carriers        45.500000  41.945289   \nCommercial Banking                                  11.737089   7.658643   \nSoftware Publishers                                 22.277228  15.068493   \nOther Computer Related Services                     24.050633  16.014235   \nComputer Systems Design Services                    15.661376   7.272727   \nCustom Computer Programming Services                20.049710   9.576613   \n\nmonth                                               change_may_to_sep  \nNAICS_2022_6_NAME                                                      \nGeneral Medical and Surgical Hospitals                       9.424520  \nUnclassified Industry                                        8.914526  \nAll Other Professional, Scientific, and Technic...           6.698565  \nEmployment Placement Agencies                                5.707114  \nOther Scientific and Technical Consulting Services           3.077163  \nAdministrative Management and General Managemen...           1.657076  \nColleges, Universities, and Professional Schools            -1.999025  \nTemporary Help Services                                     -3.063291  \nOffices of Certified Public Accountants                     -3.394684  \nDirect Health and Medical Insurance Carriers                -3.554711  \nCommercial Banking                                          -4.078446  \nSoftware Publishers                                         -7.208735  \nOther Computer Related Services                             -8.036398  \nComputer Systems Design Services                            -8.388648  \nCustom Computer Programming Services                       -10.473097  \n```\n:::\n:::\n\n\n::: {#d8e01c66 .cell message='false' execution_count=5}\n\n::: {.cell-output .cell-output-display}\n![](zichen_files/figure-html/cell-6-output-1.png){}\n:::\n:::\n\n\nThe bar chart provides a clear visual comparison of changes in remote job share across industries between May and September 2024. The results show that remote job trends were mixed across industries rather than moving in one uniform direction. Several industries experienced increases in remote job share during this period. The strongest increase appeared in General Medical and Surgical Hospitals, followed by Unclassified Industry and All Other Professional, Scientific, and Technical Services. In contrast, the steepest decline appeared in Custom Computer Programming Services, followed by Computer Systems Design Services and Other Computer Related Services.\n\n![Remote Job Shares](visualizations/change_in_remote_share_may_to_sep.png)\n\nOverall, the figure suggests that remote job share in 2024 neither increased nor decreased uniformly across the labor market. Instead, the direction and magnitude of change depended strongly on the industry. Some sectors became more remote-oriented over the period, while others showed a clear decline in remote job share.\n\n## Industry Heterogeneity and Connection to the Literature\nThis uneven pattern is consistent with prior research suggesting that remote-work opportunities vary substantially across industries rather than following a single market-wide trend [@dingel2020; @hansen2023]. In that sense, the results of this section align with a broader literature showing that remote-work adoption, feasibility, and posting behavior are shaped by sector-specific characteristics rather than by one universal labor-market shift [@dingel2020; @hansen2023; @barrero2021].\n\nOne especially interesting finding is that several computer-related industries in this sample showed declining remote share over the period, even though remote work is often associated with technology-oriented jobs. This does not mean that tech-related work is no longer remote-friendly. Instead, it suggests that remote hiring may be adjusting unevenly across sectors, with some industries expanding remote opportunities while others appear to be stabilizing or pulling back. This interpretation is also consistent with recent research showing that remote work persisted after the pandemic, but not in a uniform way across all parts of the labor market [@barrero2021].\n\n# Monthly Trends for Selected Industries\n\n## Month-to-Month Patterns\n\nAlthough the previous figure summarizes the net change in remote job share from May to September 2024, it does not show how that change developed from month to month. To better understand the time path of remote hiring, I plotted the industries with the largest increases and the largest decreases in remote job share over the period.\n\nThis figure adds an important layer to the analysis because industries may arrive at a similar final increase or decrease through very different monthly patterns. Some industries may show relatively steady movement, while others may fluctuate substantially before ending higher or lower in September than in May.\n\n::: {#67fb6f31 .cell message='false' execution_count=6}\n\n::: {.cell-output .cell-output-display}\n![](zichen_files/figure-html/cell-7-output-1.png){}\n:::\n:::\n\n\nThe line chart shows that remote job trends did not evolve in the same way across industries from month to month. Industries with positive end-of-period changes generally moved upward overall, whereas industries with negative end-of-period changes tended to move downward or remained volatile before ending lower in September than in May.\n\n![Remote Job Trends](visualizations/monthly_remote_share_selected_industries.png)\n\nSeveral upward-trending industries, such as General Medical and Surgical Hospitals and Unclassified Industry, finished the period with clearly higher remote job share than they had in May. By contrast, several computer-related industries, including Computer Systems Design Services and Custom Computer Programming Services, showed overall declines despite short-term fluctuations during the middle of the period.\n\nThis figure helps clarify that the final increase-or-decrease values reported in the previous section were not simply the result of comparing two isolated months. Instead, they reflect different monthly trajectories across industries.Taken together, the line chart reinforces the main conclusion of this section: remote work opportunities in 2024 increased in some industries and declined in others, so they cannot be described simply as moving upward or downward overall, but instead need to be analyzed at the industry level.\n\n# Conclusion\n\nThis analysis shows that remote job trends in 2024 did not move in one uniform direction across industries. Instead, remote job share increased in some industries and declined in others between May and September 2024. As a result, the answer to the research question is not that remote jobs were simply increasing or decreasing overall, but that their direction of change depended strongly on the industry.\n\nThis finding is consistent with prior research suggesting that remote-work opportunities vary substantially across sectors rather than following one common labor-market pattern [@dingel2020; @hansen2023]. In that sense, the results of this section suggest that remote work in 2024 should be understood as an industry-specific trend rather than a single market-wide movement.\n\nFor job seekers, this means that remote-work availability should be evaluated at the industry level rather than assumed to follow a general upward or downward trend. In practical terms, applicants seeking flexible work arrangements should pay close attention to sector-specific hiring patterns, because remote opportunities may be expanding in some industries while narrowing in others.\n\n",
    "supporting": [
      "zichen_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}