{
  "hash": "9584090da090a8ea49fcb04827088ff3",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Most In-Demand Skills for Data Science, Business Analytics, and ML Roles\"\nauthor: \"Omar Mohd Haris\"\ndate: today\nformat: \n  html:\n    bibliography: references.bib\n    toc: true\njupyter: python3\n---\n\n\n\n## Introduction\n\nThe data science and analytics job market continues to expand rapidly, with the U.S. Bureau of Labor Statistics projecting 36% employment growth for data scientists from 2023 to 2033. As the field matures, understanding which specific skills employers demand is critical for job seekers, educators, and program designers alike.\n\nPrevious research has examined skill requirements across analytics roles. @radovilsky2018skills conducted a comparative analysis of 1,050 job postings and found that data science roles emphasize computer systems, algorithms, and programming, while business data analytics roles place greater weight on statistical analysis and decision-making support. Similarly, @verma2019investigation performed a content analysis of job advertisements and identified SQL, Excel, and visualization tools as core requirements across analytics positions. More recently, @levendis2025business identified the most sought-after skills for business analytics roles, highlighting both technical proficiency and communication as key employer expectations.\n\nThis analysis extends that body of work by examining **72,498 job postings** from the Lightcast dataset to identify the most in-demand skills across Data Science, Business Analytics, Machine Learning, and related roles.\n\n## Data Loading\n\nWe begin by loading the Lightcast job postings dataset, which contains 131 columns covering job titles, skills, certifications, location, salary, and occupation classifications.\n\n::: {#1e86a177 .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd, json, matplotlib\nmatplotlib.use('Agg')\nimport matplotlib.pyplot as plt, numpy as np\n\ndf = pd.read_csv(\"./data/lightcast_job_postings.csv\", low_memory=False)\nprint(f\"Total postings: {len(df):,}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTotal postings: 72,498\n```\n:::\n:::\n\n\n## Filtering for Relevant Roles\n\nTo focus on data science, business analytics, and ML roles, we categorize each posting using keywords matched against the `TITLE_NAME` (Lightcast's standardized job title) and `ONET_NAME` (Bureau of Labor Statistics occupation classification) columns. This dual-column approach ensures we capture roles that may have non-standard titles but are classified under relevant O*NET codes.\n\n::: {#4c020851 .cell execution_count=2}\n``` {.python .cell-code}\nds_ml_titles = ['data scien', 'machine learn', 'deep learn', 'ai engineer',\n                'nlp engineer', 'computer vision']\nba_titles = ['business intel', 'business analy', 'bi analyst', 'bi developer']\nda_titles = ['data analy']\nde_titles = ['data engineer']\n\ndef categorize(row):\n    t = str(row['TITLE_NAME']).lower()\n    o = str(row['ONET_NAME']).lower()\n    c = t + ' ' + o\n    if any(k in c for k in ds_ml_titles): return 'Data Science / ML'\n    if any(k in c for k in ba_titles): return 'Business Analytics / BI'\n    if any(k in c for k in da_titles): return 'Data Analytics'\n    if any(k in c for k in de_titles): return 'Data Engineering'\n    return None\n\ndf['role_category'] = df.apply(categorize, axis=1)\ndf_filtered = df[df['role_category'].notna()].copy()\nprint(f\"Filtered to {len(df_filtered):,} relevant postings ({len(df_filtered)/len(df)*100:.1f}%)\\n\")\n\nprint(\"Role distribution:\")\nprint(df_filtered['role_category'].value_counts().to_string())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFiltered to 72,454 relevant postings (99.9%)\n\nRole distribution:\nrole_category\nBusiness Analytics / BI    71869\nData Science / ML            585\n```\n:::\n:::\n\n\n## Parsing Skills\n\nThe Lightcast dataset stores skills as JSON arrays within string columns (e.g., `SKILLS_NAME`, `SPECIALIZED_SKILLS_NAME`, `SOFTWARE_SKILLS_NAME`). Each posting can list multiple skills, so we parse these JSON arrays into Python lists for analysis. This approach is consistent with how @radovilsky2018skills extracted and categorized skill keywords from job posting text.\n\n::: {#b3f500b8 .cell execution_count=3}\n``` {.python .cell-code}\ndef parse_json(val):\n    if pd.isna(val): return []\n    try:\n        p = json.loads(val)\n        return p if isinstance(p, list) else []\n    except: return []\n\nfor col in ['SKILLS_NAME','SPECIALIZED_SKILLS_NAME','SOFTWARE_SKILLS_NAME']:\n    df_filtered[col+'_list'] = df_filtered[col].apply(parse_json)\n```\n:::\n\n\n## Top 30 Most In-Demand Skills (Overall)\n\nWe explode the skill lists so that each skill–posting pair becomes its own row, then count the frequency of each skill across all filtered postings. This gives us the overall demand landscape.\n\n::: {#6cf15991 .cell execution_count=4}\n``` {.python .cell-code}\nall_skills = df_filtered['SKILLS_NAME_list'].explode().dropna()\nall_skills = all_skills[all_skills != '']\nall_counts = all_skills.value_counts()\n\nprint(f\"\\n{'='*65}\")\nprint(f\"TOP 30 MOST IN-DEMAND SKILLS (DS + BA + ML + DE)\")\nprint(f\"{'='*65}\")\nprint(f\"{'Rank':<5} {'Skill':<40} {'Count':>7} {'% Posts':>8}\")\nprint(f\"{'-'*65}\")\nfor r,(s,c) in enumerate(all_counts.head(30).items(),1):\n    print(f\"{r:<5} {s:<40} {c:>7,} {c/len(df_filtered)*100:>7.1f}%\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n=================================================================\nTOP 30 MOST IN-DEMAND SKILLS (DS + BA + ML + DE)\n=================================================================\nRank  Skill                                      Count  % Posts\n-----------------------------------------------------------------\n1     Communication                             31,661    43.7%\n2     Data Analysis                             28,515    39.4%\n3     Management                                24,631    34.0%\n4     SQL (Programming Language)                21,733    30.0%\n5     Problem Solving                           18,522    25.6%\n6     Leadership                                17,561    24.2%\n7     Computer Science                          17,287    23.9%\n8     Operations                                14,767    20.4%\n9     Project Management                        13,711    18.9%\n10    Business Process                          13,278    18.3%\n11    Business Requirements                     13,035    18.0%\n12    Microsoft Excel                           12,826    17.7%\n13    Finance                                   12,438    17.2%\n14    Python (Programming Language)             12,253    16.9%\n15    SAP Applications                          12,123    16.7%\n16    Detail Oriented                           11,987    16.5%\n17    Presentations                             11,890    16.4%\n18    Dashboard                                 11,856    16.4%\n19    Tableau (Business Intelligence Software)  11,781    16.3%\n20    Planning                                  11,578    16.0%\n21    Writing                                   11,274    15.6%\n22    Power BI                                  10,850    15.0%\n23    Business Intelligence                     10,423    14.4%\n24    Research                                  10,038    13.9%\n25    Consulting                                 9,533    13.2%\n26    Agile Methodology                          9,131    12.6%\n27    Innovation                                 9,000    12.4%\n28    Troubleshooting (Problem Solving)          8,996    12.4%\n29    Information Technology                     8,852    12.2%\n30    Data Management                            8,691    12.0%\n```\n:::\n:::\n\n\n## Top 20 Software and Tools\n\nLightcast separately tags software and tool skills in the `SOFTWARE_SKILLS_NAME` column, allowing us to isolate the specific technologies employers require. The dominance of SQL in this ranking aligns with findings from @verma2019investigation, who identified SQL as the most frequently listed technical requirement in analytics job advertisements.\n\n::: {#88e26f54 .cell execution_count=5}\n``` {.python .cell-code}\nsw = df_filtered['SOFTWARE_SKILLS_NAME_list'].explode().dropna()\nsw = sw[sw != '']\nsw_counts = sw.value_counts()\n\nprint(f\"\\n{'='*65}\")\nprint(f\"TOP 20 SOFTWARE / TOOLS\")\nprint(f\"{'='*65}\")\nfor r,(s,c) in enumerate(sw_counts.head(20).items(),1):\n    print(f\"{r:<5} {s:<40} {c:>7,} {c/len(df_filtered)*100:>7.1f}%\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n=================================================================\nTOP 20 SOFTWARE / TOOLS\n=================================================================\n1     SQL (Programming Language)                21,733    30.0%\n2     Microsoft Excel                           12,826    17.7%\n3     Python (Programming Language)             12,253    16.9%\n4     SAP Applications                          12,123    16.7%\n5     Dashboard                                 11,856    16.4%\n6     Tableau (Business Intelligence Software)  11,781    16.3%\n7     Power BI                                  10,850    15.0%\n8     Microsoft Office                           7,564    10.4%\n9     Microsoft PowerPoint                       7,161     9.9%\n10    R (Programming Language)                   6,104     8.4%\n11    Microsoft Azure                            4,759     6.6%\n12    Amazon Web Services                        4,692     6.5%\n13    Oracle Cloud                               4,053     5.6%\n14    SAS (Software)                             3,539     4.9%\n15    Application Programming Interface (API)    3,509     4.8%\n16    Microsoft Access                           3,247     4.5%\n17    Relational Databases                       3,155     4.4%\n18    Salesforce                                 2,838     3.9%\n19    Java (Programming Language)                2,632     3.6%\n20    Microsoft Outlook                          2,437     3.4%\n```\n:::\n:::\n\n\n## Skills Breakdown by Role Category\n\nHere we compare the top 10 skills within each role category. This comparison reveals important differences: Data Science/ML roles prioritize Python, Machine Learning, and Statistics, while Business Analytics/BI roles emphasize Communication, Management, and Business Process knowledge. This distinction echoes the findings of @radovilsky2018skills, who noted that \"data science emphasizes computer systems, algorithms, and computer programming skills, whereas business data analytics has a substantial focus on statistical and quantitative analysis of data, and decision-making support.\" @levendis2025business similarly found that business analytics employers seek a blend of technical and communication skills.\n\n::: {#d8f88fbf .cell execution_count=6}\n``` {.python .cell-code}\nfor cat in ['Data Science / ML','Business Analytics / BI','Data Analytics','Data Engineering']:\n    sub = df_filtered[df_filtered['role_category']==cat]\n    if len(sub) < 10: continue\n    cs = sub['SKILLS_NAME_list'].explode().dropna()\n    cs = cs[cs != '']\n    top = cs.value_counts().head(10)\n    print(f\"\\n  {'='*55}\")\n    print(f\"  {cat} ({len(sub):,} postings)\")\n    print(f\"  {'='*55}\")\n    for r,(s,c) in enumerate(top.items(),1):\n        print(f\"  {r:>3}. {s:<35} {c:>6,} ({c/len(sub)*100:.1f}%)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  =======================================================\n  Data Science / ML (585 postings)\n  =======================================================\n    1. Data Science                           454 (77.6%)\n    2. Data Analysis                          435 (74.4%)\n    3. Python (Programming Language)          313 (53.5%)\n    4. SQL (Programming Language)             304 (52.0%)\n    5. Communication                          253 (43.2%)\n    6. Mathematics                            244 (41.7%)\n    7. Machine Learning                       240 (41.0%)\n    8. Statistics                             233 (39.8%)\n    9. Computer Science                       232 (39.7%)\n   10. R (Programming Language)               228 (39.0%)\n\n  =======================================================\n  Business Analytics / BI (71,869 postings)\n  =======================================================\n    1. Communication                       31,408 (43.7%)\n    2. Data Analysis                       28,080 (39.1%)\n    3. Management                          24,463 (34.0%)\n    4. SQL (Programming Language)          21,429 (29.8%)\n    5. Problem Solving                     18,346 (25.5%)\n    6. Leadership                          17,340 (24.1%)\n    7. Computer Science                    17,055 (23.7%)\n    8. Operations                          14,706 (20.5%)\n    9. Project Management                  13,599 (18.9%)\n   10. Business Process                    13,231 (18.4%)\n```\n:::\n:::\n\n\n## Plots\n\nThe four-panel chart below summarizes our findings: (1) the top 20 overall skills, (2) the top 15 software/tools, (3) the top 15 specialized technical skills, and (4) a comparison of key skills across role categories.\n\n::: {#25cd63fb .cell execution_count=7}\n``` {.python .cell-code}\nfig, axes = plt.subplots(2, 2, figsize=(20, 16))\nfig.suptitle('Most In-Demand Skills — DS, BA & ML Roles (Lightcast)',\n             fontsize=16, fontweight='bold', y=0.98)\n\n# Chart 1: Top 20 overall\nax = axes[0,0]\nt20 = all_counts.head(20)\nax.barh(range(len(t20)), t20.values, color=plt.cm.viridis(np.linspace(.3,.9,len(t20))))\nax.set_yticks(range(len(t20))); ax.set_yticklabels(t20.index, fontsize=9)\nax.invert_yaxis(); ax.set_xlabel('Postings'); ax.set_title('Top 20 Skills (All)', fontweight='bold')\n\n# Chart 2: Top 15 software\nax = axes[0,1]\nt15 = sw_counts.head(15)\nax.barh(range(len(t15)), t15.values, color=plt.cm.plasma(np.linspace(.3,.9,len(t15))))\nax.set_yticks(range(len(t15))); ax.set_yticklabels(t15.index, fontsize=9)\nax.invert_yaxis(); ax.set_xlabel('Postings'); ax.set_title('Top 15 Software/Tools', fontweight='bold')\n\n# Chart 3: Specialized\nspec = df_filtered['SPECIALIZED_SKILLS_NAME_list'].explode().dropna()\nspec = spec[spec != '']\nspec_counts = spec.value_counts().head(15)\nax = axes[1,0]\nax.barh(range(len(spec_counts)), spec_counts.values, color=plt.cm.cividis(np.linspace(.3,.9,len(spec_counts))))\nax.set_yticks(range(len(spec_counts))); ax.set_yticklabels(spec_counts.index, fontsize=9)\nax.invert_yaxis(); ax.set_xlabel('Postings'); ax.set_title('Top 15 Technical Skills', fontweight='bold')\n\n# Chart 4: Comparison across roles\nax = axes[1,1]\nkey_skills = ['Python (Programming Language)','SQL (Programming Language)',\n              'Machine Learning','Data Analysis','Tableau (Business Intelligence Software)',\n              'R (Programming Language)','Power BI','Statistics','Microsoft Excel','Data Visualization']\ncats = [c for c in ['Data Science / ML','Business Analytics / BI','Data Analytics','Data Engineering']\n        if len(df_filtered[df_filtered['role_category']==c]) > 0]\n\nx = np.arange(len(key_skills))\nw = 0.8 / len(cats)\nfor i, cat in enumerate(cats):\n    sub = df_filtered[df_filtered['role_category']==cat]\n    cc = sub['SKILLS_NAME_list'].explode().value_counts()\n    vals = [cc.get(s,0)/len(sub)*100 for s in key_skills]\n    ax.barh(x + i*w, vals, w, label=cat, alpha=0.85)\n\nax.set_yticks(x + w*(len(cats)-1)/2)\nax.set_yticklabels(key_skills, fontsize=9)\nax.invert_yaxis(); ax.set_xlabel('% of Postings')\nax.set_title('Key Skills by Role Category', fontweight='bold')\nax.legend(fontsize=8, loc='lower right')\n\nplt.tight_layout()\nplt.show()\n```\n:::\n\n\n## Conclusion\n\nOur analysis of 72,498 Lightcast job postings reveals several key findings:\n\n1. **SQL is the universal requirement** — appearing in 30% of all postings, it is the single most demanded technical skill across every role category.\n\n2. **Data Science/ML roles are distinctly more technical** — Python (53.5%), Machine Learning (41%), R (39%), and Statistics (39.8%) are all significantly more prevalent in DS/ML postings compared to BA/BI roles, confirming the skill divergence identified by @radovilsky2018skills.\n\n3. **Communication and soft skills dominate BA/BI roles** — Communication (43.7%), Management (34%), and Problem Solving (25.5%) rank highest for Business Analytics, consistent with the findings of @levendis2025business that employers value both technical and interpersonal competencies.\n\n4. **The BI tool landscape is a three-way race** — Tableau (16.3%), Power BI (15%), and Excel (17.7%) all appear in similar proportions, suggesting employers value familiarity with multiple visualization platforms rather than expertise in just one.\n\nThese findings have practical implications for analytics program curricula and for job seekers looking to align their skill development with market demand, as emphasized by @verma2019investigation.\n\n## References\n\n",
    "supporting": [
      "omar_files"
    ],
    "filters": [],
    "includes": {}
  }
}